import { TournamentGroup, GroupInfo } from "@/types";

/**
 * FIFA World Cup 2026 — 48 teams, 12 groups of 4.
 * The album physical order follows the group order (A1, A2, A3, A4, B1, …).
 * This map is generated by index: floor((teamIndex) / 4) → group letter.
 */
export const GROUP_ORDER: TournamentGroup[] = [
  "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L",
];

export const TEAM_TO_GROUP: Record<string, TournamentGroup> = {
  // Group A
  MEX: "A", RSA: "A", KOR: "A", CZE: "A",
  // Group B
  CAN: "B", BIH: "B", QAT: "B", SUI: "B",
  // Group C
  BRA: "C", MAR: "C", HAI: "C", SCO: "C",
  // Group D
  USA: "D", PAR: "D", AUS: "D", TUR: "D",
  // Group E
  GER: "E", CUW: "E", CIV: "E", ECU: "E",
  // Group F
  NED: "F", JPN: "F", SWE: "F", TUN: "F",
  // Group G
  BEL: "G", EGY: "G", IRN: "G", NZL: "G",
  // Group H
  ESP: "H", CPV: "H", KSA: "H", URU: "H",
  // Group I
  FRA: "I", SEN: "I", IRQ: "I", NOR: "I",
  // Group J
  ARG: "J", ALG: "J", AUT: "J", JOR: "J",
  // Group K
  POR: "K", COD: "K", UZB: "K", COL: "K",
  // Group L
  ENG: "L", CRO: "L", GHA: "L", PAN: "L",
};

/**
 * Per-group color tokens (CSS custom properties).
 * Designed to be perceptually distinct around the wheel at low chroma so
 * the editorial dark theme isn't broken.
 */
export const GROUPS: Record<TournamentGroup, GroupInfo> = {
  A: { code: "A", colorVar: "--grp-a" },
  B: { code: "B", colorVar: "--grp-b" },
  C: { code: "C", colorVar: "--grp-c" },
  D: { code: "D", colorVar: "--grp-d" },
  E: { code: "E", colorVar: "--grp-e" },
  F: { code: "F", colorVar: "--grp-f" },
  G: { code: "G", colorVar: "--grp-g" },
  H: { code: "H", colorVar: "--grp-h" },
  I: { code: "I", colorVar: "--grp-i" },
  J: { code: "J", colorVar: "--grp-j" },
  K: { code: "K", colorVar: "--grp-k" },
  L: { code: "L", colorVar: "--grp-l" },
};

export function getGroup(teamCode: string): TournamentGroup | null {
  return TEAM_TO_GROUP[teamCode] ?? null;
}

/** Returns the four team codes in a given group, in album order. */
export function teamsInGroup(group: TournamentGroup, allTeamCodes: string[]): string[] {
  return allTeamCodes.filter((code) => TEAM_TO_GROUP[code] === group);
}
